title: Zijia Chen, solo piano
logo: /assets/cfa_logo.png
description: Fri, May 13, 2022 | 8:00 pm <br> Room 167 <br> Boston University College of Fine Arts
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

