title: Zijia Chen, solo piano
logo: /assets/cover.jpg
description: Fri, May 13, 2022 | 8:00 pm <br> Room 167, Boston University College of Fine Arts
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

