title: Recital: Zijia Chen '22, Piano
logo: /assets/cover.jpg
description: Fri, May 13, 2022 | 8:00 pm <br> Boston University College of Fine Arts, Room 167
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
