title: Recital: Zijia Chen '22, Piano
logo: /assets/cover.jpg
description: Fri, May 13, 2022 | 8:00 pm <br> Boston University College of Fine Arts, Room 167 [Get Direction](https://www.google.com/maps/place/College+of+Fine+Arts/@42.3512868,-71.1160726,17z/data=!3m2!4b1!5s0x89e379ef46a39705:0x4a0c46466ec4f08c!4m5!3m4!1s0x89e379ef40edeceb:0x9929103aed997c8a!8m2!3d42.3512829!4d-71.1138786)
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
